export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  RESEND_VERIFICATION: '/resend-verification',
  RE_ENABLE_ACCOUNT: '/re-enable-account',
  DASHBOARD: '/dashboard',
  LEETCODE_AGENT: '/leetcode-agent',
  HACKERRANK_AGENT: '/hackerrank-agent',
  COURSES: '/courses',
  COURSES_NEW: '/courses/new',
  COURSES_HISTORY: '/courses/history',
  COURSES_DASHBOARD: '/courses/dashboard',
  DSA_PATTERN: '/dsa-pattern',
  DSA_PATTERN_NEW: '/dsa-pattern/new',
  DSA_PATTERN_DASHBOARD: '/dsa-pattern/dashboard',
  PROFILE: '/profile',
  PUBLIC_PROFILE: (username: string) => `/u/${username}`,
  ACCOUNT_SECURITY: '/settings',
  CHANGE_PASSWORD: '/settings',
  NOTIFICATIONS: '/notifications',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_USERS: '/admin/users',
  ADMIN_USER_DETAIL: (id: string) => `/admin/users/${id}`,
  ADMIN_AI_USAGE: '/admin/ai-usage',
  ADMIN_AI_USAGE_TOKENS: '/admin/ai-usage/tokens',
  ADMIN_AI_USAGE_FEATURES: '/admin/ai-usage/features',
  ADMIN_AI_USAGE_MODELS: '/admin/ai-usage/models',
  ADMIN_AI_USAGE_PROVIDERS: '/admin/ai-usage/providers',
  ADMIN_AI_USAGE_USERS: '/admin/ai-usage/users',
  ADMIN_AI_USAGE_USER: (id: string) => `/admin/ai-usage/users/${id}`,
  ADMIN_AI_USAGE_CHARTS: '/admin/ai-usage/charts',
  ADMIN_AI_USAGE_COSTS: '/admin/ai-usage/costs',
  ADMIN_AI_USAGE_REPORTS: '/admin/ai-usage/reports',
  ADMIN_ANALYTICS: '/admin/ai-usage',
  ADMIN_USAGE: '/admin/ai-usage',
  ADMIN_MODELS: '/admin/ai-usage/models',
  ADMIN_AUDIT: '/admin/audit-logs',
  ADMIN_HEALTH: '/admin/system-health',
  ADMIN_BROADCAST: '/admin/broadcast',
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    REFRESH_TOKEN: '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_EMAIL: '/auth/verify-email',
    RESEND_VERIFICATION: '/auth/resend-verification',
    ME: '/auth/me',
    CHANGE_PASSWORD: '/auth/change-password',
  },
  ACCOUNT: {
    STATUS: '/account/status',
    DISABLE: '/account/disable',
    ENABLE: '/account/enable',
    DELETE: '/account',
  },
  PROFILE: {
    ME: '/profile',
    STATISTICS: '/profile/statistics',
    AVATAR: '/profile/avatar',
    PUBLIC: (username: string) => `/profile/public/${encodeURIComponent(username)}`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    READ: (id: string) => `/notifications/${id}/read`,
    READ_ALL: '/notifications/read-all',
  },
  ADMIN: {
    LOGIN: '/admin/login',
    REFRESH_TOKEN: '/admin/refresh',
    LOGOUT: '/admin/logout',
    ME: '/admin/me',
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    USER: (id: string) => `/admin/users/${id}`,
    USER_BLOCK: (id: string) => `/admin/users/${id}/block`,
    USER_UNBLOCK: (id: string) => `/admin/users/${id}/unblock`,
    USER_ACTIVATE: (id: string) => `/admin/users/${id}/activate`,
    USER_DEACTIVATE: (id: string) => `/admin/users/${id}/deactivate`,
    ANALYTICS: '/admin/analytics',
    ANALYTICS_DASHBOARD: '/admin/analytics/dashboard',
    ANALYTICS_TOKENS: '/admin/analytics/tokens',
    ANALYTICS_FEATURES: '/admin/analytics/features',
    ANALYTICS_MODELS: '/admin/analytics/models',
    ANALYTICS_PROVIDERS: '/admin/analytics/providers',
    ANALYTICS_USERS: '/admin/analytics/users',
    ANALYTICS_USER: (id: string) => `/admin/analytics/users/${id}`,
    ANALYTICS_CHARTS: '/admin/analytics/charts',
    ANALYTICS_COSTS: '/admin/analytics/costs',
    ANALYTICS_EXPORT: '/admin/analytics/export',
    USAGE: '/admin/usage',
    MODELS: '/admin/models',
    AUDIT_LOGS: '/admin/audit-logs',
    SYSTEM_HEALTH: '/admin/system-health',
    BROADCAST: '/admin/notifications/broadcast',
  },
} as const;
